### PR TITLE
fix fm last command

### PR DESCRIPTION
**Pull request by aleclol**
idk if I did this right but it works for me now

### CODE REVIEW

**Comment by flaree** [comment]
```py
2021-04-17 16:55:26] [ERROR] red: Exception in command 'fm last'
Traceback (most recent call last):
  File "C:\Users\Jamie\Documents\pikachu-red\.venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Jamie\Documents\red-stuff\lastfm-red\lastfm\lastfm.py", line 282, in last
    await self.listening_report(ctx, "week", name)
  File "C:\Users\Jamie\Documents\red-stuff\lastfm-red\lastfm\utils.py", line 309, in listening_report
    "dt": int(dt.timestamp()),
TypeError: 'int' object is not callable```

I get the following but it appears fine on what's currently on master. What was the issue beforehand?

**Comment by aleclol** [comment]
I got this error, in addition to a few other bots in #testing
```
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Invalid variable type: value should be str, int or float, got <bound method Arrow.timestamp of <Arrow [2021-04-09T00:00:00+00:00]>> of type <class 'method'>
```
What is your arrow version? I'm wondering if they changed something and that's why it works for some people but not others.

**Comment by flaree** [comment]
Yeah, updating to latest Arrow fixed the issue.

**Review by flaree — APPROVED** [review]

**Comment by flaree** [comment]
Thanks for the PR :D

**Pull request merged**
